**Program 1: Vector Addition**

**Type 1**

In [150]:
# One-dimensional Array

import numpy as np
u = np.array([1, 2])
v = np.array([3, 4])
result = u + v
print(result)

[4 6]


In [151]:
# Two-dimensional Array

import numpy as np
u = np.array([[1, 2], [3, 4]])
v = np.array([[5, 6], [7, 8]])
result = u + v
print(result)

[[ 6  8]
 [10 12]]


In [152]:
# Three-dimensional Array

import numpy as np
u = np.array([[1, 2, 3, 5], [3, 4, 6, 8], [5, 6, 7, 10]])
v = np.array([[5, 6, 7, 2], [7, 8, 10, 1], [9, 10, 11, 8]])
result = u + v
print(result)

[[ 6  8 10  7]
 [10 12 16  9]
 [14 16 18 18]]


In [153]:
# Multidimensional Array

import numpy as np
u = np.array([[1, 2, 5, 6], [3, 4, 7, 8], [5, 6, 9, 10]])
v = np.array([[7, 8, 7, 3], [9, 10, 15, 4], [11, 12, 18, 19]])
result = u + v
print(result)

[[ 8 10 12  9]
 [12 14 22 12]
 [16 18 27 29]]


**Type 2**

**One-Dimensional Array**

In [154]:
# importing the numPy for numerical computations
import numpy as np

In [155]:
# 1D array(vector) 'u' with elements [1, 2]
# print the 1D matrix 'u'

u = np.array([1, 2])
print(u)

[1 2]


In [156]:
# 1D array(vector) 'v' with elements [3, 4]
# print the 1D matrix 'v'

v = np.array([3, 4])
print(v)

[3 4]


In [157]:
# Perform the vector addition of matrix 'u' and 'v'

vector_add = u + v

In [158]:
# print the result of the addition of two vectors

print(vector_add)

[4 6]


**Type 3**

**Two-Dimenional Array**

In [159]:
# importing the numPy for numerical computations

import numpy as np

In [160]:
# 2D array(vector) 'u' with elements [[1, 2], [3, 4]]
# print the 2D matrix 'u'

u = np.array([[1, 2], [3, 4]])
print(u)

[[1 2]
 [3 4]]


In [161]:
# 2D array(vector) 'v' with elements [[5, 6], [7, 8]]
# print the 2D matrix 'v'

v = np.array([[5, 6], [7, 8]])
print(v)

[[5 6]
 [7 8]]


In [162]:
# Perform the vector addition of matrix 'u' and 'v'

vector_add = (u + v)

In [163]:
# print the result of the addition of two vectors

print(vector_add)

[[ 6  8]
 [10 12]]


**Three-Dimensional Array**

In [164]:
# importing the numPy for numerical computations

import numpy as np

In [165]:
# 3D array(vector) 'u' with elements [[1, 2, 3, 5], [3, 4, 6, 8], [5, 6, 7, 10]]
# print the 3D matrix 'u'

u = np.array([[1, 2, 3, 5], [3, 4, 6, 8], [5, 6, 7, 10]])
print(u)

[[ 1  2  3  5]
 [ 3  4  6  8]
 [ 5  6  7 10]]


In [166]:
# 3D array(vector) 'v' with elements [[5, 6, 7, 2], [7, 8, 10, 1], [9, 10, 11, 8]]
# print the 3D matrix 'v'

v = np.array([[5, 6, 7, 2], [7, 8, 10, 1], [9, 10, 11, 8]])
print(v)

[[ 5  6  7  2]
 [ 7  8 10  1]
 [ 9 10 11  8]]


In [167]:
# Perform the vector addition of matrix 'u' and 'v'

vector_add = (u + v)

In [168]:
# print the result of the addition of two vectors

print(vector_add)

[[ 6  8 10  7]
 [10 12 16  9]
 [14 16 18 18]]


**Multidimensional Arrays**

In [169]:
# importing the numPy for numerical computations

import numpy as np

In [170]:
# Multidimensional array(vector) 'u' with elements [[1, 2, 5, 6], [3, 4, 7, 8], [5, 6, 9, 10]]
# print the multidimensional matrix 'u'

u = np.array([[1, 2, 5, 6], [3, 4, 7, 8], [5, 6, 9, 10]])
print(u)

[[ 1  2  5  6]
 [ 3  4  7  8]
 [ 5  6  9 10]]


In [171]:
# Multidimensional array(vector) 'v' with elements [[7, 8, 7, 3], [9, 10, 15, 4], [11, 12, 18, 19]]
# print the multidimensional matrix 'v'

v = np.array([[7, 8, 7, 3], [9, 10, 15, 4], [11, 12, 18, 19]])
print(v)

[[ 7  8  7  3]
 [ 9 10 15  4]
 [11 12 18 19]]


In [172]:
# Perform the vector addition of matrix 'u' and 'v'

vector_add = (u + v)

In [173]:
# print the result of the addition of two vectors

print(vector_add)

[[ 8 10 12  9]
 [12 14 22 12]
 [16 18 27 29]]
