**Program 1: Vector Addition**

**Type 1**

In [ ]:
import numpy as np
u = np.array([1, 2])
v = np.array([3, 4])
result = u + v
print(result)

[4 6]


In [31]:
import numpy as np
u = np.array([[1, 2], [3, 4]])
v = np.array([[5, 6], [7, 8]])
result = u + v
print(result)

[[ 6  8]
 [10 12]]


**Type 2**

**One Dimensional Array**

In [32]:
# importing the numPy for numerical computations
import numpy as np

In [33]:
# 1D array(vector) 'u' with elements [1, 2]
# print the 1D matrix 'u'

u = np.array([1, 2])
print(u)

[1 2]


In [34]:
# 1D array(vector) 'v' with elements [3, 4]
# print the 1D matrix 'v'

v = np.array([3, 4])
print(v)

[3 4]


In [35]:
# Perform the vector addition of matrix 'u' and 'v'

vector_add = u + v

In [36]:
# print the result of the addition of two vectors

print(vector_add)

[4 6]


**Type 3**

**Two Dimenional Array**

In [37]:
# importing the numPy for numerical computations

import numpy as np

In [38]:
# 2D array(vector) 'u' with elements [[1, 2], [3, 4]]
# print the 2D matrix 'u'

u = np.array([[1, 2], [3, 4]])
print(u)

[[1 2]
 [3 4]]


In [39]:
# 2D array(vector) 'v' with elements [[5, 6], [7, 8]]
# print the 2D matrix 'v'

v = np.array([[5, 6], [7, 8]])
print(v)

[[5 6]
 [7 8]]


In [40]:
# Perform the vector addition of matrix 'u' and 'v'

vector_add = (u + v)

In [41]:
# print the result of the addition of two vectors

print(vector_add)

[[ 6  8]
 [10 12]]
