**Program 2: Scalar Multiplication of a Vector**

**Type 1**

In [71]:
import numpy as np
alpha = 3
v = np.array([2, -1])
scal_mul = alpha * v
print(scal_mul)

[ 6 -3]


In [72]:
import numpy as np
alpha = 3
v = np.array([[2, -1], [3, 4]])
scal_mul = alpha * v
print(scal_mul)

[[ 6 -3]
 [ 9 12]]


In [73]:
import numpy as np
alpha = 3
v = np.array([[2, -1, 5, 7], [3, 4, 8, 2]])
scal_mul = alpha * v
print(scal_mul)

[[ 6 -3 15 21]
 [ 9 12 24  6]]


**Type 2**

In [74]:
# importing the numPy for numerical computations

import numpy as np

In [75]:
# define the scalar value 'alpha'

alpha = 3
print(alpha)

3


In [76]:
# define the 1D array 'u' with the elements [2, -1]

u = np.array([2, -1])
print(u)

[ 2 -1]


In [77]:
# Perform the scalar multiplication of 'alpha' and 'u'

scal_mul = alpha * u

In [78]:
# Print the resulting vector after scalar multiplication

print(scal_mul)

[ 6 -3]


**Type 3**

In [79]:
# importing the numPy for numerical computations

import numpy as np

In [80]:
# define the scalar value 'alpha'

alpha = 3
print(alpha)

3


In [81]:
# define the 2D array 'u' with the elements [[2, -1], [3, 4]]

u = np.array([[2, -1], [3, 4]])
print(u)

[[ 2 -1]
 [ 3  4]]


In [82]:
# Perform the scalar multiplication of 'alpha' and 'u'

scal_mul = alpha * u

In [83]:
# Print the resulting vector after scalar multiplication

print(scal_mul)

[[ 6 -3]
 [ 9 12]]


**Type 4**

In [84]:
# importing the numPy for numerical computations

import numpy as np

In [85]:
# define the scalar value 'alpha'

alpha = 3
print(alpha)

3


In [86]:
# define the 3D array 'u' with the elements [[2, -1, 5, 7], [3, 4, 8, 2]]

u = np.array([[2, -1, 5, 7], [3, 4, 8, 2]])
print(u)

[[ 2 -1  5  7]
 [ 3  4  8  2]]


In [87]:
# Perform the scalar multiplication of 'alpha' and 'u'

scal_mul = alpha * u

In [88]:
# Print the resulting vector after scalar multiplication

print(scal_mul)

[[ 6 -3 15 21]
 [ 9 12 24  6]]
