**Program 3: Dot Product**

**Type 1**

In [21]:
import numpy as np
u = np.array([1, 2])
v = np.array([3, 4])
dot_prod = np.dot(u, v)
print('The dot product of the given matrix is: ', dot_prod)

The dot product of the given matrix is:  11


In [22]:
import numpy as np
u = np.array([[1, 2], [3, 4]])
v = np.array([[5, 6], [7, 8]])
dot_prod = np.dot(u, v)
print('The dot product of the given matrix:', dot_prod)

# Element-Wise Multiplication and Dot Product

elementwise_dot = np.sum(np.multiply(u, v))
print('Elementwise and dot product is:', elementwise_dot)

The dot product of the given matrix: [[19 22]
 [43 50]]
Elementwise and dot product is: 70


In [23]:
import numpy as np
u = np.array([[1, 2, 1], [3, 4, 2], [9, 6, 5]])
v = np.array([[6, 1, 5], [8, 6, 4], [7, 5, 3]])
dot_prod = np.dot(u, v)
print('The dot product of the given matrix:', dot_prod)

# Element-Wise Multiplication and Dot Product

elementwise_dot = np.sum(np.multiply(u, v))
print('Elementwise and dot product is: ', elementwise_dot)

The dot product of the given matrix: [[ 29  18  16]
 [ 64  37  37]
 [137  70  84]]
Elementwise and dot product is:  177


**Type 2**

In [24]:
# importing the NumPy library for numerical operations

import numpy as np

In [25]:
# define 1D array(vector) 'u' with elements [1, 2]

u = np.array([1, 2])
print(u)

[1 2]


In [26]:
# define 1D array(vector) 'v' with elements [3, 4]

v = np.array([3, 4])
print(v)

[3 4]


In [27]:
# compute the dot product of vectors 'u' and 'v'
# Dot product formula: u.v = u[0] * v[0]

dot_prod = np.dot(u, v)

In [28]:
# print the resulting scalar value after completing the dot product

print(dot_prod)

11


**Type 3**

In [29]:
# importing the NumPy library for numerical operations

import numpy as np

In [30]:
# define 2D array(vector) 'u' with elements [[1, 2], [3, 4]]

u = np.array([[1, 2], [3, 4]])
print(u)

[[1 2]
 [3 4]]


In [31]:
# define 2D array(vector) 'v' with elements [[5, 6], [7, 8]]

v = np.array([[5, 6], [7, 8]])
print(v)

[[5 6]
 [7 8]]


In [32]:
# compute the dot product of vectors 'u' and 'v'
# Dot product formula: u.v = (v[0] * u[0] +  v[1] * u[1])

dot_prod = np.dot(u, v)

In [33]:
# print the result after completing the dot product
# The dot product for 2D arrays is equivalent to matrix multiplication
print(dot_prod)

[[19 22]
 [43 50]]


In [34]:
# Element-Wise Multiplication and Dot Product

elementwise_dot = np.sum(np.multiply(u, v))
print('Elementwise and dot product is: ', elementwise_dot)

Elementwise and dot product is:  70


**Type 4**

In [35]:
# importing the NumPy library for numerical operations

import numpy as np

In [36]:
# define 3D array(vector) 'u' with elements [[1, 2, 1], [3, 4, 2], [9, 6, 5]]

u = np.array([[1, 2, 1], [3, 4, 2], [9, 6, 5]])
print(u)

[[1 2 1]
 [3 4 2]
 [9 6 5]]


In [37]:
# define 3D array(vector) 'v' with elements [[6, 1, 5], [8, 6, 4], [7, 5, 3]]

v = np.array([[6, 1, 5], [8, 6, 4], [7, 5, 3]])
print(v)

[[6 1 5]
 [8 6 4]
 [7 5 3]]


In [38]:
# compute the dot product of vectors 'u' and 'v'
# Dot product formula: u.v = (u[0] * v[0]) + (u[1] * v[1]) + (u[2] * v[2])

dot_prod = np.dot(u, v)

In [39]:
# print the result after completing the dot product
# The dot product for 3D arrays is equivalent to matrix multiplication

print(dot_prod)

[[ 29  18  16]
 [ 64  37  37]
 [137  70  84]]


In [40]:
# Element-Wise Multiplication and Dot Product

elementwise_dot = np.sum(np.multiply(u, v))
print('Elementwise and dot product is: ', elementwise_dot)

Elementwise and dot product is:  177
