**Program 4: Cross Product**

**Type 1**

In [49]:
import numpy as np
u = np.array([1, 0, 0])
v = np.array([0, 1, 0])
cross_prod = np.cross(u, v)
print(cross_prod)

[0 0 1]


In [65]:
import numpy as np
u = np.array([[1, 0, 0], [1, 0, 0], [1, 0, 0]])
v = np.array([[1, 1, 0], [0, 0, 1], [1, 0, 1]])
cross_prod = np.cross(u, v)
print(cross_prod)

[[ 0  0  1]
 [ 0 -1  0]
 [ 0 -1  0]]


In [66]:
import numpy as np
u = np.array([[[1, 0, 0], [1, 0, 1], [1, 1, 0]], [[1, 1, 1], [1, 1, 1], [1, 1, 1]]])
v = np.array([[[1, 1, 0], [1, 1, 1], [1, 1, 0]], [[1, 1, 1], [1, 1, 0], [1, 1, 1]]])
cross_prod = np.cross(u, v)
print(cross_prod)

[[[ 0  0  1]
  [-1  0  1]
  [ 0  0  0]]

 [[ 0  0  0]
  [-1  1  0]
  [ 0  0  0]]]


**Type 2**

In [50]:
# importing the numPy library for numerical computations

import numpy as np

In [51]:
# define 1D array(vector) 'u' with elements [1, 0, 0] representing a 3D vector

u = np.array([1, 0, 0])
print(u)

[1 0 0]


In [52]:
# define 1D array(vector) 'v' with elements [0, 1, 0] representing a 3D vector

v = np.array([0, 1, 0])
print(v)

[0 1 0]


In [53]:
# compute the cross product of 'u' and 'v'
# Cross Product in 3D space results in a vector perpendicular to both 'u' and 'v'

cross_prod = np.cross(u, v)

In [54]:
# print the result of the vector after performing the cross product

print(cross_prod)

[0 0 1]


**Type 3**

In [55]:
# importing the numPy library for numerical computations

import numpy as np

In [56]:
# define 2D array(vector) 'u' with elements [[1, 0, 0], [1, 0, 0], [1, 0, 0]] representing a 3D vector

u = np.array([[1, 0, 0], [1, 0, 0], [1, 0, 0]])
print(u)

[[1 0 0]
 [1 0 0]
 [1 0 0]]


In [57]:
# define 2D array(vector) 'v' with elements [[1, 1, 0], [0, 0, 1], [1, 0, 1]] representing a 3D vector

v = np.array([[1, 1, 0], [0, 0, 1], [1, 0, 1]])
print(v)

[[1 1 0]
 [0 0 1]
 [1 0 1]]


In [58]:
# compute the cross product of 'u' and 'v'
# Cross Product in 3D space results in a vector perpendicular to both 'u' and 'v'

cross_prod = np.cross(u, v)

In [59]:
# print the result of the vector after performing the cross product

print(cross_prod)

[[ 0  0  1]
 [ 0 -1  0]
 [ 0 -1  0]]


**Type 4**

In [60]:
# importing the numPy library for numerical computations

import numpy as np

In [61]:
# define 3D array(vector) 'u' with elements [[[1, 0, 0], [1, 0, 1], [1, 1, 0]], [[1, 1, 1], [1, 1, 1], [1, 1, 1]]] representing a 3D vector

u = np.array([[[1, 0, 0], [1, 0, 1], [1, 1, 0]], [[1, 1, 1], [1, 1, 1], [1, 1, 1]]])
print(u)

[[[1 0 0]
  [1 0 1]
  [1 1 0]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [62]:
# define 3D array(vector) 'v' with elements [[[1, 1, 0], [1, 1, 1], [1, 1, 0]], [[1, 1, 1], [1, 1, 0], [1, 1, 1]]] representing a 3D vector

v = np.array([[[1, 1, 0], [1, 1, 1], [1, 1, 0]], [[1, 1, 1], [1, 1, 0], [1, 1, 1]]])
print(v)

[[[1 1 0]
  [1 1 1]
  [1 1 0]]

 [[1 1 1]
  [1 1 0]
  [1 1 1]]]


In [63]:
# compute the cross product of 'u' and 'v'
# Cross Product in 3D space results in a vector perpendicular to both 'u' and 'v'

cross_prod = np.cross(u, v)

In [64]:
# print the result of the vector after performing the cross product

print(cross_prod)

[[[ 0  0  1]
  [-1  0  1]
  [ 0  0  0]]

 [[ 0  0  0]
  [-1  1  0]
  [ 0  0  0]]]
